name: On Push Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check:
    uses: ./.github/workflows/check.yml

  deploy:
    needs: check
    uses: ./.github/workflows/deploy.yml
